# Regis managed services, pinned to ap-south-1.
#
# Scope: the stateful pieces the application cannot recreate itself — Postgres,
# Redis, the evidence bucket, and the KMS key that encrypts them. Compute
# (ECS/App Runner) is deliberately not here yet; see README.md.
#
# The database password is NOT in Terraform state as a literal: RDS generates and
# stores it in Secrets Manager, and the app reads it from there at boot.

terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Application = "regis"
      Environment = var.env
      ManagedBy   = "terraform"
      DataClass   = "customer-compliance-records"
    }
  }
}

locals {
  name = "regis-${var.env}"
}

# --------------------------------------------------------------------------
# Encryption
# --------------------------------------------------------------------------
resource "aws_kms_key" "regis" {
  description             = "${local.name} — evidence, database and cache encryption"
  enable_key_rotation     = true
  deletion_window_in_days = 30
}

resource "aws_kms_alias" "regis" {
  name          = "alias/${local.name}"
  target_key_id = aws_kms_key.regis.key_id
}

# --------------------------------------------------------------------------
# Evidence storage
# --------------------------------------------------------------------------
resource "aws_s3_bucket" "evidence" {
  bucket = "${local.name}-evidence"
}

# Evidence backs an append-only audit trail; a deleted or overwritten object
# breaks the trail an RBI inspection would follow.
resource "aws_s3_bucket_versioning" "evidence" {
  bucket = aws_s3_bucket.evidence.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "evidence" {
  bucket = aws_s3_bucket.evidence.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.regis.arn
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "evidence" {
  bucket                  = aws_s3_bucket.evidence.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# The app hands out presigned URLs; nothing should ever reach the bucket over
# plain HTTP.
resource "aws_s3_bucket_policy" "evidence_tls_only" {
  bucket = aws_s3_bucket.evidence.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "DenyInsecureTransport"
      Effect    = "Deny"
      Principal = "*"
      Action    = "s3:*"
      Resource = [
        aws_s3_bucket.evidence.arn,
        "${aws_s3_bucket.evidence.arn}/*",
      ]
      Condition = { Bool = { "aws:SecureTransport" = "false" } }
    }]
  })
}

# --------------------------------------------------------------------------
# Postgres — the RLS tenant boundary lives here
# --------------------------------------------------------------------------
resource "aws_db_subnet_group" "regis" {
  name       = local.name
  subnet_ids = var.private_subnet_ids
}

resource "aws_security_group" "db" {
  name   = "${local.name}-db"
  vpc_id = var.vpc_id

  ingress {
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [var.app_security_group_id]
  }
}

resource "aws_db_instance" "regis" {
  identifier     = local.name
  engine         = "postgres"
  engine_version = "16"
  instance_class = var.db_instance_class

  allocated_storage     = var.db_allocated_storage_gb
  max_allocated_storage = var.db_allocated_storage_gb * 5
  storage_encrypted     = true
  kms_key_id            = aws_kms_key.regis.arn

  db_name  = "regis"
  username = "regis"
  # Generated by RDS into Secrets Manager, so no password literal enters state.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = aws_kms_key.regis.arn

  db_subnet_group_name   = aws_db_subnet_group.regis.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false

  multi_az                = var.env == "prod"
  backup_retention_period = var.env == "prod" ? 30 : 7
  deletion_protection     = var.env == "prod"
  skip_final_snapshot     = var.env != "prod"
  final_snapshot_identifier = var.env == "prod" ? "${local.name}-final" : null

  auto_minor_version_upgrade = true
  performance_insights_enabled = var.env == "prod"

  # RLS is FORCEd per table by migration 0002; the app must never connect as a
  # superuser, because superusers bypass row-level security entirely.
  lifecycle {
    ignore_changes = [engine_version]
  }
}

# --------------------------------------------------------------------------
# Redis — Arq queue and the login rate limiter
# --------------------------------------------------------------------------
resource "aws_elasticache_subnet_group" "regis" {
  name       = local.name
  subnet_ids = var.private_subnet_ids
}

resource "aws_security_group" "redis" {
  name   = "${local.name}-redis"
  vpc_id = var.vpc_id

  ingress {
    from_port       = 6379
    to_port         = 6379
    protocol        = "tcp"
    security_groups = [var.app_security_group_id]
  }
}

resource "aws_elasticache_replication_group" "regis" {
  replication_group_id = local.name
  description          = "${local.name} — Arq queue and rate-limit counters"
  engine               = "redis"
  engine_version       = "7.1"
  node_type            = var.redis_node_type
  num_cache_clusters   = var.env == "prod" ? 2 : 1
  port                 = 6379

  subnet_group_name  = aws_elasticache_subnet_group.regis.name
  security_group_ids = [aws_security_group.redis.id]

  at_rest_encryption_enabled = true
  kms_key_id                 = aws_kms_key.regis.arn
  transit_encryption_enabled = true

  automatic_failover_enabled = var.env == "prod"
}
